version : "3"
services:
  web-app:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    container_name: web-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    restart: "no"
   
  unopim-q:
    build:
      context: .
      dockerfile: dockerfiles/q.Dockerfile
    container_name: unopim-q
    volumes:
      - .:/var/www/html
    restart: unless-stopped
   
